# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.IntegerField(max_length=200, unique=True)),
                ('ingredient_name', models.CharField(max_length=200, unique=True)),
                ('user_preference', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('calories', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('fiber', models.FloatField(default=0)),
                ('sugar', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField(max_length=200, unique=True)),
                ('recipe_name', models.CharField(max_length=200, unique=True)),
                ('number_steps', models.IntegerField(default=0)),
                ('instructions', models.TextField()),
                ('ingredient', models.ManyToManyField(to='foodapp.Ingredient')),
            ],
        ),
    ]
