# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_ingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='iid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rid',
            field=models.IntegerField(unique=True),
        ),
    ]
