# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_auto_20170217_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='package_size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='serving_size',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
