# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_auto_20170217_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_id', models.IntegerField(unique=True)),
                ('ingredient_name', models.CharField(max_length=200)),
                ('recipe_id', models.IntegerField(default=0)),
                ('ingredient_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredient_id',
        ),
    ]
