# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_auto_20170220_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_id',
            field=models.ManyToManyField(to='foodapp.Relationship'),
        ),
    ]
