# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0011_auto_20170301_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
