# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0014_auto_20170306_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
