# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0017_auto_20170306_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ranking',
            field=models.FloatField(default=0),
        ),
    ]
